<a href="https://colab.research.google.com/github/Muchee-ai/Data-preparation/blob/main/Replacing-values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

map() - orqali qiymatlarni moslash(almashtirish)

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/refs/heads/main/automobile_data_nan.csv")
df.head()

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0

In [4]:
df['num-of-cylinders'].unique()

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

In [7]:
dict={'two':2, 'three':3, 'four':4, 'five':5, "six":6, "eight":8, 'twelve':12}
df['cylinders']=df['num-of-cylinders'].map(dict)
df

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0,4
1,1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0,4
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0,6
3,3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0,4
4,4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0,5
...,...,...,...,...,...,...,...,...,...,...,...
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0,4
57,82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0,4
58,86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0,4
59,87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0,4
60,88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0,4

In [8]:
df['price']

0     13495.0
1     16500.0
2     16500.0
3     13950.0
4     17450.0
       ...
56     7975.0
57     7995.0
58     9995.0
59    12940.0
60    13415.0
Name: price, Length: 61, dtype: float64

replace() - istalgan qiymatlari almashtirish uchun